site_name: AI-VERDE Manual & Resource Site
site_description: This site serves as the manual and resource site for AI-VERDE (aka VERDE), our classroom chatbot, providing guides for using the service.
site_author: CyVerse and Data Science Institute
site_url: https://aiverde-docs.cyverse.ai

# Repository
repo_name: AI-VERDE Docs
repo_url: https://github.com/CyVerse-learning-materials/verde-docs
edit_uri: edit/main/docs/
# Copyright
copyright: "Copyright &copy; 2025 CyVerse"

# Configuration
theme:
  name: material
  highlightjs: true
  font:
    text: Roboto
    code: Regular

  # Features
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow

  # 404 page
  static_templates:
    - 404.html

  # Search feature
  include_search_page: false
  search_index_only: true

  # Palette and theme (uses personalized colours)
  language:
    en

    # Palette toggle for light mode
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # palette:
  #   primary: custom
  #   accent: custom
  logo: assets/verde-letter-logo.png
  icon:
    logo: material/cogs
  favicon: assets/verde-letter-logo.png

# Page tree
nav:
  - AI-VERDE Chat:
      - Welcome: index.md
      - Getting Started: getting-started.md
      - Current CyVerse Models: models-current.md
      - Chat History: chat-history.md
  - AI-VERDE API:
      - Getting Started:
          - What is the AI-VERDE API: api/index.md
          - Obtaining your AI-VERDE API Key: api/api-token.md
          - Getting a List of Models: api/api-key-models.md
      - Using Your API Key in Code:
          - LangChain: api/api-token-langchain.md
          - LlamaIndex: api/api-token-llamaindex.md
      - Using CLI Coding Assistants:
          - Claude Code Router: api/claude-code-router.md
          - Aider: api/aider.md
          - Claude Code (using Anthropic Models): api/api-key-claude.md
      - Using IDEs:
          - VSCode: api/api-token-vscode.md
          - Jupyter: api/api-token-jupyter.md
      - Using Desktop Clients:
          - ChatboxAI.app: api/chatboxai.md
  - FAQ:
      - FAQ: faq.md
  - For Instructors (and staff):
      - Getting Started: instructors/getting-started.md
    # - Creating a Course: instructors/creating-a-course.md
    # - Managing a Course: instructors/managing-a-course.md
    # - Troubleshooting: instructors/troubleshooting.md

# Theme Extras
extra_css:
  - stylesheets/extra.css

# Extra Plugins
plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True

# Extensions (leave as is)
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  # - content.code.copy
  # - open-in-new-tab
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
